# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Crawler

on:
  schedule:
    - cron: '0/10 0-14 * * *'
  push:
    branches: [ main, data ]
    paths:
      - 'BeijingUniversalCrawler.jar'
      - '.github/workflows/crawler.yml'
  workflow_dispatch:

jobs:
  crawler:
    runs-on: ubuntu-latest
    concurrency:
      group: crawler
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Crawler
        run: |
          git config --global user.email "ssiori@gmail.com"
          git config --global user.name "${{ github.actor }}"
          git branch -a
          git fetch origin data
          git checkout data
          java -jar BeijingUniversalCrawler.jar
      - name: Git
        run: |
          git diff
          git add *.json
          git status
          git commit -m "crawler"
          git push origin data
